"""Smoke tests for src/cartographer/discovery/plugins/go_scanner.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_discovery_plugins_go_scanner():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.discovery.plugins.go_scanner")
    assert mod is not None
