"""Smoke tests for src/cartographer/drafters/constrain_drafter.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_drafters_constrain_drafter():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.drafters.constrain_drafter")
    assert mod is not None
