"""Smoke tests for src/cartographer/compatibility/arbiter_checker.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_compatibility_arbiter_checker():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.compatibility.arbiter_checker")
    assert mod is not None
