"""Smoke tests for src/cartographer/discovery/sensitive_fields.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_discovery_sensitive_fields():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.discovery.sensitive_fields")
    assert mod is not None

def test_load_patterns_is_callable():
    """Function load_patterns exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.discovery.sensitive_fields")
    fn = getattr(mod, "load_patterns", None)
    assert fn is not None, "'load_patterns' not found in cartographer.discovery.sensitive_fields"
    assert callable(fn)
