"""Smoke tests for src/cartographer/discovery/scanner.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_discovery_scanner():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.discovery.scanner")
    assert mod is not None

def test_scan_source_is_callable():
    """Function scan_source exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.discovery.scanner")
    fn = getattr(mod, "scan_source", None)
    assert fn is not None, "'scan_source' not found in cartographer.discovery.scanner"
    assert callable(fn)
