"""Smoke tests for src/cartographer/models.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_models():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.models")
    assert mod is not None
