"""Smoke tests for src/cartographer/config/loader.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_config_loader():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.config.loader")
    assert mod is not None

def test_find_config_is_callable():
    """Function find_config exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.config.loader")
    fn = getattr(mod, "find_config", None)
    assert fn is not None, "'find_config' not found in cartographer.config.loader"
    assert callable(fn)

def test_load_config_is_callable():
    """Function load_config exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.config.loader")
    fn = getattr(mod, "load_config", None)
    assert fn is not None, "'load_config' not found in cartographer.config.loader"
    assert callable(fn)

def test_write_default_config_is_callable():
    """Function write_default_config exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.config.loader")
    fn = getattr(mod, "write_default_config", None)
    assert fn is not None, "'write_default_config' not found in cartographer.config.loader"
    assert callable(fn)
