"""Smoke tests for src/cartographer/drafters/pact_drafter.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_drafters_pact_drafter():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.drafters.pact_drafter")
    assert mod is not None
