"""Smoke tests for src/cartographer/compatibility/base.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_compatibility_base():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.compatibility.base")
    assert mod is not None
