"""Smoke tests for src/cartographer/cli/main.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_cli_main():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.cli.main")
    assert mod is not None

def test_main_is_callable():
    """Function main exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.cli.main")
    fn = getattr(mod, "main", None)
    assert fn is not None, "'main' not found in cartographer.cli.main"
    assert callable(fn)

def test_init_is_callable():
    """Function init exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.cli.main")
    fn = getattr(mod, "init", None)
    assert fn is not None, "'init' not found in cartographer.cli.main"
    assert callable(fn)

def test_discover_is_callable():
    """Function discover exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.cli.main")
    fn = getattr(mod, "discover", None)
    assert fn is not None, "'discover' not found in cartographer.cli.main"
    assert callable(fn)

def test_check_is_callable():
    """Function check exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.cli.main")
    fn = getattr(mod, "check", None)
    assert fn is not None, "'check' not found in cartographer.cli.main"
    assert callable(fn)

def test_report_is_callable():
    """Function report exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.cli.main")
    fn = getattr(mod, "report", None)
    assert fn is not None, "'report' not found in cartographer.cli.main"
    assert callable(fn)

def test_adopt_is_callable():
    """Function adopt exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.cli.main")
    fn = getattr(mod, "adopt", None)
    assert fn is not None, "'adopt' not found in cartographer.cli.main"
    assert callable(fn)

def test_drafts_is_callable():
    """Function drafts exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.cli.main")
    fn = getattr(mod, "drafts", None)
    assert fn is not None, "'drafts' not found in cartographer.cli.main"
    assert callable(fn)

def test_drafts_list_is_callable():
    """Function drafts_list exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.cli.main")
    fn = getattr(mod, "drafts_list", None)
    assert fn is not None, "'drafts_list' not found in cartographer.cli.main"
    assert callable(fn)

def test_drafts_show_is_callable():
    """Function drafts_show exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.cli.main")
    fn = getattr(mod, "drafts_show", None)
    assert fn is not None, "'drafts_show' not found in cartographer.cli.main"
    assert callable(fn)
