"""Smoke tests for src/cartographer/compatibility/pact_checker.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_compatibility_pact_checker():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.compatibility.pact_checker")
    assert mod is not None
