"""Smoke tests for src/cartographer/report/generator.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_report_generator():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.report.generator")
    assert mod is not None

def test_build_report_is_callable():
    """Function build_report exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.report.generator")
    fn = getattr(mod, "build_report", None)
    assert fn is not None, "'build_report' not found in cartographer.report.generator"
    assert callable(fn)

def test_format_text_is_callable():
    """Function format_text exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.report.generator")
    fn = getattr(mod, "format_text", None)
    assert fn is not None, "'format_text' not found in cartographer.report.generator"
    assert callable(fn)

def test_format_json_is_callable():
    """Function format_json exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.report.generator")
    fn = getattr(mod, "format_json", None)
    assert fn is not None, "'format_json' not found in cartographer.report.generator"
    assert callable(fn)

def test_save_report_is_callable():
    """Function save_report exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.report.generator")
    fn = getattr(mod, "save_report", None)
    assert fn is not None, "'save_report' not found in cartographer.report.generator"
    assert callable(fn)
