"""Smoke tests for src/cartographer/drafters/base.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_drafters_base():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.drafters.base")
    assert mod is not None
