"""Smoke tests for src/cartographer/discovery/pact_keys.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_discovery_pact_keys():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.discovery.pact_keys")
    assert mod is not None
