"""Smoke tests for src/cartographer/compatibility/runner.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_compatibility_runner():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.compatibility.runner")
    assert mod is not None

def test_run_checks_is_callable():
    """Function run_checks exists and is callable."""
    import importlib
    mod = importlib.import_module("cartographer.compatibility.runner")
    fn = getattr(mod, "run_checks", None)
    assert fn is not None, "'run_checks' not found in cartographer.compatibility.runner"
    assert callable(fn)
