"""Smoke tests for src/cartographer/discovery/plugins/ruby_scanner.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_discovery_plugins_ruby_scanner():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.discovery.plugins.ruby_scanner")
    assert mod is not None
