"""Smoke tests for src/cartographer/discovery/plugins/base.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_discovery_plugins_base():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.discovery.plugins.base")
    assert mod is not None
