"""Smoke tests for src/cartographer/discovery/plugins/python_scanner.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_discovery_plugins_python_scanner():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.discovery.plugins.python_scanner")
    assert mod is not None
