"""Smoke tests for src/cartographer/discovery/env_vars.py (auto-generated by pact adopt)."""

import pytest

def test_import_cartographer_discovery_env_vars():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("cartographer.discovery.env_vars")
    assert mod is not None
