"""Constrain artifact drafter — generates draft Constrain artifacts from discoveries."""

from __future__ import annotations

from pathlib import Path

import yaml

from cartographer.drafters.base import Drafter
from cartographer.models import DiscoveryResult


class ConstrainDrafter(Drafter):
    def draft(self, result: DiscoveryResult, output_dir: Path) -> list[Path]:
        constrain_dir = output_dir / "constrain"
        constrain_dir.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []

        # Draft prompt
        prompt_path = constrain_dir / "prompt_draft.md"
        with open(prompt_path, "w") as f:
            f.write(_build_prompt(result))
        written.append(prompt_path)

        # Draft component map
        component_map = _build_component_map(result)
        map_path = constrain_dir / "component_map_draft.yaml"
        with open(map_path, "w") as f:
            yaml.dump(component_map, f, default_flow_style=False, sort_keys=False)
        written.append(map_path)

        # Draft constraints from error patterns and validations
        constraints = _build_constraints(result)
        if constraints:
            constraints_path = constrain_dir / "constraints_draft.yaml"
            with open(constraints_path, "w") as f:
                yaml.dump(constraints, f, default_flow_style=False, sort_keys=False)
            written.append(constraints_path)

        # Draft trust policy (minimal, all at floor)
        trust = _build_trust_policy(result)
        trust_path = constrain_dir / "trust_policy_draft.yaml"
        with open(trust_path, "w") as f:
            yaml.dump(trust, f, default_flow_style=False, sort_keys=False)
        written.append(trust_path)

        # Draft schema hints
        if result.models or result.env_vars:
            hints = _build_schema_hints(result)
            hints_path = constrain_dir / "schema_hints_draft.yaml"
            with open(hints_path, "w") as f:
                yaml.dump(hints, f, default_flow_style=False, sort_keys=False)
            written.append(hints_path)

        return written


def _build_prompt(result: DiscoveryResult) -> str:
    sections = ["# System Discovery\n"]
    sections.append(
        f"Discovered {len(result.components)} components, "
        f"{len(result.models)} data models, "
        f"{len(result.routes)} API routes, "
        f"{len(result.pact_keys)} PACT keys.\n\n"
    )

    if result.components:
        sections.append("## Components\n\n")
        for c in result.components[:30]:
            sections.append(f"- **{c.name}** ({c.type.value}) — {c.source_file}:{c.line}\n")
        sections.append("\n")

    if result.routes:
        sections.append("## API Routes\n\n")
        for r in result.routes[:30]:
            sections.append(f"- `{r.method} {r.path}` — {r.framework} ({r.source_file}:{r.line})\n")
        sections.append("\n")

    if result.models:
        sections.append("## Data Models\n\n")
        for m in result.models[:30]:
            sections.append(f"- **{m.name}** ({m.orm}) — {m.source_file}:{m.line}\n")
        sections.append("\n")

    sections.append(
        "\n_This is a draft generated by Cartographer. It is not a substitute "
        "for running Constrain — it reduces the time a Constrain session takes "
        "by pre-populating discoverable facts._\n"
    )
    return "".join(sections)


def _build_component_map(result: DiscoveryResult) -> dict:
    components = []
    for c in result.components:
        components.append({
            "_draft": True,
            "_generated_by": "cartographer",
            "name": c.name.lower().replace(" ", "_"),
            "type": c.type.value,
            "source_file": c.source_file,
            "_confidence": c.confidence.value,
            "data_access": {"_note": "Must be filled during Constrain session"},
            "authority": {"_note": "Must be filled during Constrain session"},
            "dependencies": c.dependencies,
        })
    return {"_draft": True, "_generated_by": "cartographer", "components": components, "edges": []}


def _build_constraints(result: DiscoveryResult) -> list[dict]:
    constraints = []
    idx = 1

    # If there are sensitive fields, add a data protection constraint
    if result.sensitive_fields:
        tiers = set(sf.classification_hint for sf in result.sensitive_fields)
        constraints.append({
            "_draft": True,
            "_generated_by": "cartographer",
            "id": f"C{idx:03d}",
            "boundary": "Sensitive data handling",
            "condition": f"Fields classified as {', '.join(sorted(tiers))} must be protected",
            "violation": "Unprotected access to classified fields",
            "severity": "must",
            "_confidence": "low",
            "_note": "Inferred from field name patterns — human must confirm classifications",
        })
        idx += 1

    return constraints


def _build_trust_policy(result: DiscoveryResult) -> dict:
    tiers = set()
    for sf in result.sensitive_fields:
        tiers.add(sf.classification_hint)

    return {
        "_draft": True,
        "_generated_by": "cartographer",
        "trust": {
            "floor": 0.15,
            "_note": "Minimal trust policy — all values at floor. Refine during Constrain session.",
        },
        "classifications": sorted(tiers) if tiers else ["PUBLIC"],
    }


def _build_schema_hints(result: DiscoveryResult) -> dict:
    backends = []
    for ev in result.env_vars:
        if ev.backend_hint:
            backends.append({
                "env_var": ev.name,
                "type": ev.backend_hint,
                "_confidence": ev.confidence.value,
            })

    field_hints = []
    for sf in result.sensitive_fields:
        field_hints.append({
            "field": sf.field_name,
            "classification": sf.classification_hint,
            "_confidence": sf.confidence.value,
            "_note": f"Matched pattern: {sf.pattern_matched}",
        })

    return {
        "_draft": True,
        "_generated_by": "cartographer",
        "storage_backends": backends,
        "field_hints": field_hints[:50],  # Cap to avoid oversized files
    }
